---
- name: Install chocolatey
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

- name: Enable the FireEye chocolatey repository
  win_shell: |
    choco sources add -n=fireeye -s https://www.myget.org/F/fireeye/api/v2 --priority 1
    choco feature enable -n allowGlobalConfirmation
    choco feature enable -n allowEmptyChecksums

- name: Install the spicy chocolatey tools
  win_chocolatey:
    name:
      - notepadplusplus
      - 7zip
      - conemu
      - dotpeek
      - dotnet4.6.2
      - dotnet4.7.2
      - cmder.fireeye
      - git
      - adobereader.fireeye
      - jre8
      - wireshark.fireeye
      - cyberchef.flare
      - firefox.fireeye
      - vscode.fireeye
      - vcpython27
      - python2.x86.nopath.flare
      - python2
      - python3
      - golang
      - dep
      - ruby
      - ruby2.devkit
      - adexplorer.fireeye
      - rsat.fireeye
      - tortoisesvn
      - sysinternals.fireeye
      - nmap.fireeye
      - SublimeText3.fireeye
      - ilspy.flare
      - dnspy.flare
      - autoit.fireeye
      - ScreenToGif.fireeye
      - telnet.fireeye
      - citrix-receiver.fireeye
      - sqlitebrowser.fireeye
      - putty.fireeye
      - vmwarevsphereclient.fireeye
      - vmware-horizon-client.fireeye
      - mobaxterm.fireeye
      - processhacker.flare
      - vlc.fireeye
      - yed.fireeye
      - hashcat.fireeye
      - 7zip
      - Greenshot.fireeye
      - winscp.fireeye
      - keepass.fireeye
      - zap.fireeye
      - vnc-viewer.fireeye
      - hashcat.fireeye
      - hashcheck
      - qbittorrent
      - dbeaver
      - hfsexplorer
      - lockhunter
      - simplednscrypt.fireeye
      - heidisql.fireeye
      - hfs.fireeye
      - neo4j-community.fireeye
      - sqlserver-cmdlineutils.fireeye
      - peview.flare
      - shellcode_launcher.flare
      - x64dbg.fireeye
      - windbg.fireeye
      - windbg.kenstheme.flare
      - proxycap.fireeye
      - windump.fireeye
      - hexchat.fireeye
      - pidgin.fireeye
      - thunderbird.fireeye
      - gimp.fireeye
      - apimonitor.fireeye
      - orca.fireeye
      - fiddler.fireeye
      - notepadplusplus
      - notepadplusplus-textfx.fireeye
      - hxd.fireeye
      - metasploit.flare
      - burp.free.fireeye
      - kali.fireeye
      - kali_windowsbinaries.fireeye
      - nirlauncher.fireeye
      - unxUtils
      - virustotaluploader
      - tor-browser.fireeye
      - ADACLScanner.fireeye
      - ADAPE-Script.fireeye
      - ADOffline.fireeye
      - ADRecon.fireeye
      - amass.docker.fireeye
      - ASREPRoast.fireeye
      - BloodHound.fireeye
      - BeRoot.fireeye
      - Bloodhound-Custom-Queries.fireeye
      - CheckPlease.fireeye
      - CredNinja.fireeye
      - DAMP.fireeye
      - Dumpert.fireeye
      - contextmenu.fireeye
      - CrackMapExec.fireeye
      - CrackMapExecWin.fireeye
      - demiguise.fireeye
      - docker.fireeye
      - DotNetToJScript.fireeye
      - DomainPasswordSpray.fireeye
      - DSInternals.fireeye
      - Egress-Assess.fireeye
      - explorersuite.flare
      - Exchange-AD-Privesc.fireeye
      - flare-floss.fireeye
      - fuzzdb.fireeye
      - GadgetToJScript.fireeye
      - Generate-Macro.fireeye
      - Get-LAPSPasswords.fireeye
      - Get-ReconInfo.fireeye
      - GoBuster.fireeye
      - GoFetch.fireeye
      - gowitness.fireeye
      - Grouper2.fireeye
      - impacket.fireeye
      - impacket-examples-windows.fireeye
      - Internal-Monologue.fireeye
      - Inveigh.fireeye
      - Seclists.fireeye
      - Invoke-ACLPwn.fireeye
      - Invoke-CradleCrafter.fireeye
      - Invoke-DCOM.fireeye
      - Invoke-DOSfuscation.fireeye
      - Invoke-Obfuscation.fireeye
      - Invoke-Phant0m.fireeye
      - Invoke-PowerThIEf.fireeye
      - Invoke-PSImage.fireeye
      - Invoke-TheHash.fireeye
      - KeeFarce.fireeye
      - KeeThief.fireeye
      - LAPSToolkit.fireeye
      - luckystrike.fireeye
      - MailSniper.fireeye
      - metatwin.fireeye
      - Mimikatz.fireeye
      - mimikittenz.fireeye
      - Net-GPPPassword.fireeye
      - NetshHelperBeacon.fireeye
      - nishang.fireeye
      - nps.fireeye
      - OffensiveCSharp.fireeye
      - pafishmacro.fireeye
      - PayloadsAllTheThings.fireeye
      - powercat.fireeye
      - PowerLessShell.fireeye
      - PowerLurk.fireeye
      - PowerPriv.fireeye
      - PowerShdll.fireeye
      - PowerShell-Suite.fireeye
      - PowerSploit.fireeye
      - PowerUpSQL.fireeye
      - PowerView.fireeye
      - Privesc.fireeye
      - PrivExchange.fireeye
      - PSAmsi.fireeye
      - PSAttack.fireeye
      - PSBits.fireeye
      - PSReflect.fireeye
      - Recon-AD.fireeye
      - RedTeamPowershellScripts.fireeye
      - RiskySPN.fireeye
      - Rubeus.fireeye
      - ruler.fireeye
      - SafetyKatz.fireeye
      - Seatbelt.fireeye
      - SessionGopher.fireeye
      - Sharp-Suite.fireeye
      - SharpDPAPI.fireeye
      - SharpDump.fireeye
      - SharpExchangePriv.fireeye
      - SharpHound.fireeye
      - SharpRoast.fireeye
      - SharpUp.fireeye
      - SharpView.fireeye
      - SharpWMI.fireeye
      - spiderfoot.docker.fireeye
      - SpoolerScanner.fireeye
      - StarFighters.fireeye
      - SpoolSample.fireeye
      - SysWhispers.fireeye
      - ThreadContinue.fireeye
      - TikiTorch.fireeye
      - UACME.fireeye
      - vssown.fireeye
      - WMImplant.fireeye
      - WMIOps.fireeye
      - zBang.fireeye
      - ad-control-paths.fireeye
      - defendercheck.fireeye
      - dnsrecon.fireeye
      - EvilClippy.fireeye
      - NtdsAudit.fireeye
      - SharpExec.fireeye
      - subdomain-bruteforce.fireeye
      - wfuzz.fireeye
      - FOCA.fireeye
      - juicy-potato.fireeye
      - NetRipper.fireeye
      - Watson.fireeye
      - vulcan.fireeye
      - RobotsDisallowed.fireeye
      - Probable-Wordlists.fireeye
      - PwnedPasswordsNTLM.fireeye
      - RottenPotatoNG.fireeye
      - SharpClipHistory.fireeye
      - SharpSploit.fireeye
      - openvpn.fireeye
    state: present